export type WorkCategory =
  | "All"
  | "AI"
  | "Web"
  | "Mobile"
  | "DevOps"
  | "Finance";

export interface WorkItem {
  id: string;
  title: string;
  description: string;
  service: string;
  category: WorkCategory;
  serviceSlug: string;
  outcome: string;
  accentHex: string;
  tags: string[];
  featured?: boolean;
}

export const FEATURED_WORK: WorkItem[] = [
  {
    id: "recruitment-ai",
    title: "AI Recruitment Platform",
    description:
      "End-to-end AI-powered hiring platform that screens resumes, ranks candidates, and schedules interviews autonomously — eliminating 80% of manual HR overhead.",
    service: "AI & Machine Learning",
    category: "AI",
    serviceSlug: "ai",
    outcome: "60% reduction in time-to-hire",
    accentHex: "#00F5FF",
    tags: ["LLM", "RAG", "Python", "Next.js", "Pinecone"],
    featured: true,
  },
  {
    id: "saas-analytics",
    title: "Multi-Tenant Analytics SaaS",
    description:
      "Real-time analytics dashboard with role-based access control, custom report builder, and white-label support for 10k+ concurrent users across 200+ organisations.",
    service: "Web Development",
    category: "Web",
    serviceSlug: "web",
    outcome: "10k+ active users on launch day",
    accentHex: "#3B82F6",
    tags: ["Next.js", "tRPC", "PostgreSQL", "Prisma", "Redis"],
    featured: true,
  },
  {
    id: "sports-companion",
    title: "Live Sports Companion App",
    description:
      "React Native app with real-time match scoring, fantasy leagues, push notifications, and in-app purchases — cleared App Review on first submission.",
    service: "Mobile Apps",
    category: "Mobile",
    serviceSlug: "mobile",
    outcome: "50k+ downloads in month one",
    accentHex: "#7C3AED",
    tags: ["React Native", "Expo", "Firebase", "WebSockets", "Stripe"],
    featured: true,
  },
  {
    id: "payment-gateway",
    title: "Payment Gateway Integration",
    description:
      "Custom payment infrastructure for a B2B SaaS — multi-currency support, automated reconciliation, PCI-DSS compliant tokenisation, and real-time fraud scoring.",
    service: "Fintech Engineering",
    category: "Finance",
    serviceSlug: "finance",
    outcome: "$2M+ in transactions processed on day one",
    accentHex: "#FFB800",
    tags: ["Stripe", "Plaid", "Node.js", "PostgreSQL", "PCI DSS"],
  },
  {
    id: "devops-platform",
    title: "Internal Developer Platform",
    description:
      "Self-service deployment portal with GitOps workflows, environment provisioning, cost dashboards, and automated rollback — cut release cycles from days to minutes.",
    service: "DevOps & Cloud",
    category: "DevOps",
    serviceSlug: "devops",
    outcome: "Deploy time cut from 3 days to 8 minutes",
    accentHex: "#10B981",
    tags: ["Kubernetes", "Terraform", "ArgoCD", "AWS", "Datadog"],
  },
  {
    id: "ecommerce-platform",
    title: "Headless E-Commerce Platform",
    description:
      "High-performance headless storefront for a DTC brand handling 50k SKUs, with AI-powered search, personalised recommendations, and sub-second page loads.",
    service: "Web Development",
    category: "Web",
    serviceSlug: "web",
    outcome: "42% uplift in conversion rate",
    accentHex: "#3B82F6",
    tags: ["Next.js", "Algolia", "Shopify API", "Vercel", "Tailwind"],
  },
  {
    id: "ai-document-processor",
    title: "AI Document Processing Engine",
    description:
      "Intelligent document pipeline for a legal-tech firm — extracts clauses, flags risks, classifies contracts, and generates summaries with 97% accuracy at scale.",
    service: "AI & Machine Learning",
    category: "AI",
    serviceSlug: "ai",
    outcome: "97% extraction accuracy, 10× faster reviews",
    accentHex: "#00F5FF",
    tags: ["GPT-4o", "LangChain", "Python", "FastAPI", "S3"],
  },
  {
    id: "bookkeeping-automation",
    title: "Bookkeeping Automation Suite",
    description:
      "Automated month-end close for a Series-A fintech — bank feed reconciliation, expense categorisation, payroll sync, and one-click financial reports.",
    service: "Bookkeeping & Payroll",
    category: "Finance",
    serviceSlug: "finance",
    outcome: "Month-end close from 5 days to same day",
    accentHex: "#FFB800",
    tags: ["QuickBooks API", "Plaid", "Python", "Airflow", "PostgreSQL"],
  },
  {
    id: "fitness-app",
    title: "AI-Powered Fitness App",
    description:
      "Cross-platform mobile app with personalised workout plans generated by ML, computer vision form analysis, social challenges, and wearable integration.",
    service: "Mobile Apps",
    category: "Mobile",
    serviceSlug: "mobile",
    outcome: "4.8★ rating, 200k+ installs",
    accentHex: "#7C3AED",
    tags: [
      "React Native",
      "TensorFlow Lite",
      "HealthKit",
      "Node.js",
      "Supabase",
    ],
  },
];

export const WORK_CATEGORIES: WorkCategory[] = [
  "All",
  "AI",
  "Web",
  "Mobile",
  "DevOps",
  "Finance",
];
